Added DB week2 homework
sandhana14/hyf-homework pull request #16
Opened 2021-01-19 19:12 UTC by sandhana14

2021-01-23 16:23 UTC, aina21 requested changes
good job :)

2021-01-23 16:23 UTC, aina21 commented on databases/week2/DB_week2.sql
> +CREATE TABLE class(id INT PRIMARY KEY,name VARCHAR(50),begins DATE,ends DATE);
It's better to add AUTO_INCREMENT for primary keys :)

2021-01-23 16:23 UTC, aina21 commented on databases/week2/DB_week2.sql
> +JOIN user_task ON task.id=user_task.task_id
I believe we don't have a user_task table, you can join task table to the user as it has user_id.

2021-01-23 16:23 UTC, aina21 commented on databases/week2/DB_week2.sql
> +JOIN user_task ON task.id=user_task.task_id
same here!
try without user_task, and the result should be zero :)

2021-01-23 16:23 UTC, aina21 commented on databases/week2/DB_week2.sql
> +JOIN user_task ON task.id = user_task.task_id
same

2021-01-23 16:30 UTC, aina21 approved these changes

2021-01-27 10:19 UTC, soujanyapolavarapu reviewed
good job dear :)

2021-01-27 10:19 UTC, soujanyapolavarapu commented on databases/week2/DB_week2.sql
> +
good job sandhana :) I have reviewed your queries...looks clean and prefect.

2021-02-03 14:26 UTC, merged