Added javascript homework for week2
sandhana14/hyf-homework pull request #6
Opened 2020-11-03 11:32 UTC by sandhana14

2020-11-05 19:52 UTC, aina21 requested changes
Good job 👍

2020-11-05 19:52 UTC, aina21 commented on javascript/javascript1/week2/scriptweek2.js
> +    if(firstname !== "" || lastname !== ""){
you don't need this condition :)

2020-11-05 19:52 UTC, aina21 commented on javascript/javascript1/week2/scriptweek2.js
> +        let formalName = "Lord";
use const

2020-11-05 19:52 UTC, aina21 commented on javascript/javascript1/week2/scriptweek2.js
> +let day = new Date();
use const, always use const until it doesn't let you

2020-11-05 19:52 UTC, aina21 commented on javascript/javascript1/week2/scriptweek2.js
> +    if(temp>20){
what about time temperature is equal to 20 0r 10 or 1

2020-11-05 19:52 UTC, aina21 commented on javascript/javascript1/week2/scriptweek2.js
> +    if(studentName === "Queen Margrethe II"){
what if we add Queen Margrethe II twice?

2020-11-05 19:52 UTC, aina21 commented on javascript/javascript1/week2/scriptweek2.js
> +        if(class07Students.length < 6 || class07Students.length>=6){
Do you need this condition?

2020-11-05 19:52 UTC, aina21 commented on javascript/javascript1/week2/scriptweek2.js
> +    if(candyType === "sweet"){
maybe switch is more readable here.

2020-11-05 19:52 UTC, aina21 commented on javascript/javascript1/week2/scriptweek2.js
> +        let price = weight*0.5;
It is better to define price before if as you use in out of scope

2020-11-05 19:52 UTC, aina21 commented on javascript/javascript1/week2/scriptweek2.js
> +if(canBuyMoreCandy() === true){
try to check with if(canBuyMoreCandy())

2020-11-07 20:51 UTC, sandhana14 commented on javascript/javascript1/week2/scriptweek2.js
> +if(canBuyMoreCandy() === true){
Hi Ida, I tried what you said here. According to my understanding, Since this above function is returning the boolean value, no need to use true. It will automatically consider as true in if condition. Am I right?

2020-11-07 20:57 UTC, sandhana14 commented on javascript/javascript1/week2/scriptweek2.js
> +        if(class07Students.length < 6 || class07Students.length>=6){
Yes Ida, I think it is needed. Because I want to add queen when the class doesn't have space (which is more than 6 students in the class)and has space(which is less than 6 students in the class).

2020-11-14 19:29 UTC, merged