Added jsweek4 homework files.
sandhana14/hyf-homework pull request #8
Opened 2020-11-18 12:36 UTC by sandhana14

2020-11-27 15:32 UTC, ajgcph2019 requested changes

2020-11-27 15:32 UTC, ajgcph2019 commented on javascript/javascript1/week4/index.html
> +</html>
Good job. I have given feedback as below

2020-11-27 15:32 UTC, ajgcph2019 commented on javascript/javascript1/week4/jsweek4.js
> +
Do you use Prettier for formatting ? The function code block and the parenthesis dont seem formatted

2020-11-27 15:32 UTC, ajgcph2019 commented on javascript/javascript1/week4/jsweek4.js
> +    var nextChris = new Date(2020, 11, 25);
Try to use const or let instead of var

2020-11-27 15:32 UTC, ajgcph2019 commented on javascript/javascript1/week4/jsweek4.js
> +    if(commandArray[3] === "+"){
Use meaningful variable names

2020-11-27 15:54 UTC, ajgcph2019 commented on javascript/javascript1/week4/jsweek4.js
> +    if(name == ""){
What you did is correct. There is also an alternative like below 
There are string methods like 'startsWith' and 'endsWith'.
For example 
 const commandWords = inputString.split(' ');

  if (inputString.startsWith('hello my name is')) {
    name = commandWords[commandWords.length - 1];
    return `Nice to meet you ${name}`;
  }

2020-11-29 16:41 UTC, sandhana14 commented on javascript/javascript1/week4/jsweek4.js
> +
Hi Anna, No, I haven't used it. Hereafter, I will use it

2020-11-29 16:43 UTC, sandhana14 commented on javascript/javascript1/week4/jsweek4.js
> +    if(name == ""){
ok, Thank you for letting me know

2020-12-01 08:38 UTC, merged